# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Places' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Places
pod 'SVProgressHUD', '~> 2.2'
pod 'Alamofire', '~> 4.5'
pod 'AlamofireImage', '~> 3.3'
pod 'SlideMenuControllerSwift', '~> 3.0'
pod 'SwiftyJSON', '4.0.0-alpha.1'

end
